repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.84.0
    hooks:
      - id: terraform_fmt
        files: '^infra/.*\.tf$'
      - id: terraform_validate
        files: '^infra/.*\.tf$'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.18.0
    hooks:
      - id: eslint
        files: '^webapp/.*\.(ts|tsx|vue)$'
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-plugin-vue@9.20.0
          - eslint-plugin-prettier@5.5.4
          - eslint-config-prettier@10.1.8
          - '@vue/eslint-config-typescript@12.0.0'
          - typescript@5.3.3
          - vue-eslint-parser@9.4.3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '^webapp/.*\.(ts|tsx|vue|json|css|html)$'
        additional_dependencies:
          - prettier@3.1.0
