repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.84.0
    hooks:
      - id: terraform_fmt
        files: '^infra/.*\.tf$'
      - id: terraform_validate
        files: '^infra/.*\.tf$'
