name: infra PR Validation

on:
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -diff -recursive

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: a5e1bd80-d295-419d-8586-39dbbc1e615b
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: 673b4b78-11f8-4da7-8199-8a3ca1545cf1
          ARM_TENANT_ID: d6bc13d4-9f71-4cce-a8cf-87039d919f0c

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -out=tfplan.txt > full_plan.log || true
          grep -A30 "Terraform will perform the following actions:" full_plan.log > plan.log || echo "No changes detected." > plan.log
        env:
          ARM_CLIENT_ID: a5e1bd80-d295-419d-8586-39dbbc1e615b
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: 673b4b78-11f8-4da7-8199-8a3ca1545cf1
          ARM_TENANT_ID: d6bc13d4-9f71-4cce-a8cf-87039d919f0c
          TF_VAR_static_web_app_client_secret: ${{ secrets.STATIC_WEB_APP_CLIENT_SECRET }}

      - name: Check for Terraform changes and comment
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: infra/plan.log
          header: "Terraform Plan Summary"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
